import json
import math
from collections import Counter

from repo_paths import data_file, repo_file

def get_first_digit(n):
    if n is None or n <= 0:
        return None
    s = str(n).replace('.', '').lstrip('0')
    return int(s[0]) if s else None

def calculate_benford_probs():
    return {d: math.log10(1 + 1/d) for d in range(1, 10)}

def analyze_benford(data_list):
    digits = [get_first_digit(x) for x in data_list]
    digits = [d for d in digits if d is not None]
    
    if not digits:
        return None
    
    counts = Counter(digits)
    total = len(digits)
    observed = {d: counts.get(d, 0) / total for d in range(1, 10)}
    expected = calculate_benford_probs()
    
    mad = sum(abs(observed[d] - expected[d]) for d in range(1, 10)) / 9
    
    # Nigrini MAD Thresholds: 
    # < 0.006: Close conformity
    # 0.006 - 0.012: Acceptable conformity
    # 0.012 - 0.015: Marginally acceptable
    # > 0.015: Non-conformity
    
    status = "Close Conformity"
    if mad > 0.015:
        status = "Non-Conformity (CRITICAL)"
    elif mad > 0.012:
        status = "Marginally Acceptable"
    elif mad > 0.006:
        status = "Acceptable Conformity"
        
    return {
        "total_samples": total,
        "observed_dist": observed,
        "expected_dist": expected,
        "mad": mad,
        "status": status
    }

def main():
    data_path = data_file("mizan_index_data.json")
    if not data_path.exists():
        print(f"Error: {data_path} not found.")
        return

    with data_path.open('r', encoding='utf-8') as f:
        data = json.load(f)

    enrollments = []
    locations = []

    for country, info in data.get("countries", {}).items():
        for trial in info.get("sample_trials", []):
            if "enrollment" in trial:
                enrollments.append(trial["enrollment"])
            if "locations_count" in trial:
                locations.append(trial["locations_count"])

    enrollment_audit = analyze_benford(enrollments)
    locations_audit = analyze_benford(locations)

    results = {
        "project": "AfricaRCT",
        "audit_type": "Benford's Law Forensic",
        "timestamp": "2026-04-19",
        "metrics": {
            "enrollment": enrollment_audit,
            "locations_count": locations_audit
        }
    }

    output_path = repo_file("sentinel_audit_results.json")
    with output_path.open('w', encoding='utf-8') as f:
        json.dump(results, f, indent=2)

    print(f"Audit complete. Results saved to {output_path}")
    
    # Generate TruthCert Summary
    summary_path = repo_file("SENTINEL_SUMMARY.md")
    with summary_path.open('w', encoding='utf-8') as f:
        f.write("# Sentinel Forensic Audit: Hidden Realities (AfricaRCT)\n\n")
        f.write(f"**Date**: 2026-04-19\n")
        f.write(f"**Dataset**: `mizan_index_data.json`\n\n")
        
        for metric, audit in results["metrics"].items():
            if audit:
                f.write(f"## Metric: {metric}\n")
                f.write(f"- **Samples**: {audit['total_samples']}\n")
                f.write(f"- **MAD**: {audit['mad']:.6f}\n")
                f.write(f"- **Status**: {audit['status']}\n\n")
        
        f.write("--- \n*Generated by Sentinel Audit Engine*")

if __name__ == "__main__":
    main()
